const HANDLE_TOGGLE_CLUE = "HANDLE_TOGGLE_CLUE";
const HANDLE_PILL_LOGIC = "HANDLE_PILL_LOGIC";
const PAUSE_TIMER = "PAUSE_TIMER";
const START_TIMER = "START_TIMER";
const RESTART_TIMER = "RESTART_TIMER";
const CLUE_TEXT_TRANSMISSION = "CLUE_TEXT_TRANSMISSION";

module.exports = {
  HANDLE_PILL_LOGIC,
  HANDLE_TOGGLE_CLUE,
  PAUSE_TIMER,
  START_TIMER,
  RESTART_TIMER,
  CLUE_TEXT_TRANSMISSION,
};
