const HANDLE_TOGGLE_CLUE = "HANDLE_TOGGLE_CLUE";
const PAUSE_TIMER = "PAUSE_TIMER";
const START_TIMER = "START_TIMER";
const RESTART_TIMER = "RESTART_TIMER";

module.exports = {
  HANDLE_TOGGLE_CLUE,
  PAUSE_TIMER,
  START_TIMER,
  RESTART_TIMER,
};
