const HANDLE_TOGGLE_CLUE = "HANDLE_TOGGLE_CLUE";
const HANDLE_PILL_LOGIC = "HANDLE_PILL_LOGIC";
const PAUSE_TIMER = "PAUSE_TIMER";
const START_TIMER = "START_TIMER";
const RESTART_TIMER = "RESTART_TIMER";
const TOKEN_STATE = "TOKEN_STATE";
const PILL_ERROR = "PILL_ERROR";
const PILL_UI = "PILL_UI";

module.exports = {
  HANDLE_PILL_LOGIC,
  HANDLE_TOGGLE_CLUE,
  PAUSE_TIMER,
  START_TIMER,
  RESTART_TIMER,
  TOKEN_STATE,
  PILL_ERROR,
  PILL_UI,
};
